import redis from '@/lib/redis';
import { auditStatsKey, normalizeUsername } from '@/lib/audit';
import { DevWrappedStats } from '@/types/github';

function isValidStats(value: unknown): value is DevWrappedStats {
  if (!value || typeof value !== 'object') return false;
  const stats = value as Partial<DevWrappedStats>;
  return (
    typeof stats.user?.login === 'string' &&
    Array.isArray(stats.languages) &&
    typeof stats.overview === 'object' &&
    typeof stats.streak === 'object' &&
    typeof stats.pullRequests === 'object'
  );
}

export async function getDevWrappedStats(username: string): Promise<DevWrappedStats | null> {
  // Normalize exactly like the enqueue path so cache keys always line up
  const handle = normalizeUsername(username);

  try {
    // Read the pre-cached result generated by the Go worker engine
    const cachedData = await redis?.get(auditStatsKey(handle));

    if (!cachedData) {
      return null;
    }

    // Parse defensively: a corrupt/foreign payload must never throw up the tree
    const parsed: unknown =
      typeof cachedData === 'string' ? JSON.parse(cachedData) : cachedData;

    if (isValidStats(parsed)) {
      return parsed;
    }

    console.error(`[Cache CORRUPT] Unexpected stats payload shape for: ${handle}`);
    return null;
  } catch (err) {
    console.error(`Failed to retrieve stats for ${handle}:`, err);
    return null;
  }
}
